version: '3.8'

services:
  # Main aggregator service
  aggregator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pub-sub-aggregator
    ports:
      - "8080:8080"
    volumes:
      # Persist database across container restarts
      - ./data:/app/data
    environment:
      - DEDUP_DB_PATH=/app/data/dedup.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - aggregator-network
    restart: unless-stopped

  # Publisher service (sends events to aggregator)
  publisher:
    build:
      context: .
      dockerfile: Dockerfile.publisher
    container_name: event-publisher
    depends_on:
      aggregator:
        condition: service_healthy
    environment:
      - AGGREGATOR_URL=http://aggregator:8080
    networks:
      - aggregator-network
    restart: "no"  # Run once and exit

networks:
  aggregator-network:
    driver: bridge
    internal: false  # Allow external access for testing
