version: '3.9'

services:
  aggregator:
    build: .
    container_name: pub-sub-aggregator
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - DEDUP_DB_PATH=/app/data/dedup.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    stop_grace_period: 10s
    restart: unless-stopped
    networks:
      - aggregator-network

  
  publisher:
    build:
      context: .
      dockerfile: Dockerfile.publisher
    container_name: event-publisher
    depends_on:
      aggregator:
        condition: service_healthy
    environment:
      - AGGREGATOR_URL=http://aggregator:8080
    networks:
      - aggregator-network
    profiles: ["tools"]
    restart: "no"

networks:
  aggregator-network:
    driver: bridge
